# Used as an override for prod to make S3 self hosted
version: '3'
services:
  s3:
    image: minio/minio
    restart: 'unless-stopped'
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
    volumes:
      - s3data:/data
    command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://s3:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      /usr/bin/mc mb --ignore-existing myminio/${S3_BUCKET};
      exit 0;
      "

volumes:
  s3data:
