name = "pdx-tools"
workers_dev = false
route = "pdx.tools/*"
compatibility_date = "2021-09-18"
main = "workers-site/worker/script.js"

[build]
command = "cd workers-site && npm run build"

[site]
bucket = "./out"

# Ignore JS map files as they tend to be used for debugging, but more
# importantly they will trip cloudflare KV value size of 10MB
exclude = ["*.js.map"]

[env.dev]
name = "rakaly-dev"
route = "dev.pdx.tools/*"
