[package]
name = "wasm-vic3"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["miniz", "zstd/fat-lto"]
miniz = ["vic3save/miniz"]
libdeflate = ["vic3save/libdeflate"]

[dependencies]
jomini = "0.22"
schemas = { path = "../schemas" }
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = "0.5"
serde = { version = "1", features = ["derive"] }
vic3save = { path = "../vic3save" }
js-sys = "0.3"
zstd = { version = "0.12.3", default-features = false }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false