[package]
name = "eu4game"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[features]
default = ["embedded", "miniz"]
miniz = ["eu4save/miniz"]
libdeflate = ["eu4save/libdeflate"]
zstd-fat-lto = ["zstd/fat-lto"]
embedded = []

[dependencies]
jomini = { version = "0.21" }
eu4save = { git = "https://github.com/rakaly/eu4save.git", default-features = false }
schemas = { path = "../schemas", features = ["inline"] }
tarsave = { path = "../tarsave" }
serde = { version = "1", features = ["derive"] }
serde_path_to_error = "0.1"
highway = "1"
base64 = "0.13"
thiserror = "1"
zstd = { version = "0.12.3", default-features = false }

[dev-dependencies]
attohttpc = "0.25"
walkdir = "2"
zip = { version =  "0.6", default-features = false, features = ["deflate"] }

[build-dependencies]
regex = "1.5"