name: CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!github.event.pull_request.head.repo.fork || contains(github.event.pull_request.labels.*.name, 'safe to test')"
    env:
      CARGO_TERM_VERBOSE: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache assets
      uses: actions/cache@v3
      with:
        path: |
          assets/game-bundles
          assets/eu4-saves
          src/vic3save/assets
        key: asset-cache

    # https://nextjs.org/docs/messages/no-cache#github-actions
    - name: Cache Next.js build
      uses: actions/cache@v3
      with:
        path: src/app/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Build and run Dev Container task
      uses: devcontainers/ci@v0.3
      env:
        ASSETS_ACCESS_KEY: ${{ secrets.ASSETS_ACCESS_KEY }}
        ASSETS_SECRET_KEY: ${{ secrets.ASSETS_SECRET_KEY }}
        GH_PAT: ${{ secrets.GH_PAT }}
      with:
        imageName: ghcr.io/pdx-tools/devcontainer
        env: |
          ASSETS_ACCESS_KEY
          ASSETS_SECRET_KEY
          GH_PAT
        runCmd: |
          just admin-sync-assets && \
          just package-all && \
          just build-wasm-dev && \
          just test && \
          just build

    - name: Push to container registry
      if: github.ref == 'refs/heads/master'
      run: docker push ghcr.io/pdx-tools/pdx-tools:nightly
